version: '3.1'

services:
  db:
    image: postgres:16
    container_name: easystay-postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: easystay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EasyStayDB